/* clang-format off */
/* Autogenerated.  Do not edit. */

#pragma once

#include <vector>
#include <string>
#include <memory>

namespace discogs {
namespace parser {

/* class_fragment.h */
#ifdef RJSP_WIDE_CHAR
typedef std::wstring string_t;
typedef wchar_t char_t;
#else
typedef std::string string_t;
typedef char char_t;
#endif

} // namespace discogs
} // namespace parser
/* clang-format on */
