/* clang-format off */
/* Autogenerated.  Do not edit. */

#pragma once

#include "class_common.hpp"
#include "paginate.hpp"
#include "basic_information.hpp"

namespace discogs {
namespace parser {
namespace folder_releases {

class release {
public:
	release(): id(0), instance_id(0), rating(0) {}
	~release(){}
	release(const release &rhs) = default;
	release(release &&rhs) noexcept = default;
	release& operator=(const release &rhs) = default;
	release& operator=(release &&rhs) noexcept = default;

	int id;
	int instance_id;
	int rating;
	string_t date_added;
	basic_information::basic_information basic_information_;
};

class container {
public:
	container(){}
	container(std::vector<release> &&release__, paginate::pagination &&pagination__) noexcept
		:release_(std::move(release__)),
		pages(std::move(pagination__))  {}
	container(const container &rhs) = default;
	container(container &&rhs) noexcept = default;
	container& operator=(const container &rhs) = default;
	container& operator=(container &&rhs) noexcept = default;

	std::vector<release> release_;
	paginate::pagination pages;

};

} // namespace discogs
} // namespace parser
} // namespace folder_releases

/* clang-format on */
