/* clang-format off */
/* Autogenerated.  Do not edit. */
#pragma once

#include <memory>
#include <string>
#include <cstring>
#include <vector>

#ifdef PLATFORM_WCHAR
typedef rapidjson::UTF16<> rjs_UTF_t;
#else
typedef rapidjson::UTF8<> rjs_UTF_t;
#endif

/* clang-format on */
